---
title: "fifa"
output: html_document
---

```{r packages}
# Load all of the packages that you end up using
# in your analysis in this code chunk.
library(ggplot2)
library(lsr)
library(GGally)
library(RColorBrewer)
library(grid)
library(gridExtra)
library(ellipse)
library(MASS)
library(ellipse)
library(lattice)
library(memisc)
library(reshape2)
library(scales)
library(dplyr)
#install.packages('GGally')
```




```{r}
fifa <- read.csv('fifa.csv', sep=';')
fifa$Project.Approval.Date <- as.Date(fifa$Project.Approval.Date, format="%d.%m.%Y")
fifa$Project.Approval.Year <- format(fifa$Project.Approval.Date, "%Y")
str(fifa)

write.table(fifa, file = "fifa1.csv", append = FALSE, quote = F, sep = ",",
            eol = "\n", na = "NA", dec = ".", row.names = TRUE,
            col.names = TRUE, qmethod = c("escape", "double"),
            fileEncoding = "")

```

##Общая статистика
658 проектов
197 стран
508717453 Суммарный бюджет проектов
773126.8 - средний бюджет проекта
5e+05 - медианный бюджет проекта
```{r}
summary(fifa)
dim(fifa)
mean(fifa$Total.Budget)
median(fifa$Total.Budget)
min(fifa$Total.Budget)
max(fifa$Total.Budget)
sum(fifa$Total.Budget)

```


```{r}
###Черновик. EDA
ggplot( data = fifa, aes(x = Project.Approval.Year)) + geom_histogram(color='white', fill="steelblue")

ggplot( data = fifa, aes(x = Project.Approval.Year, y = Total.Budget, color=fifa$Continent)) + geom_point(size=3, alpha=0.5, position="jitter")+ scale_y_sqrt()


ggplot( data = fifa, aes(x = diff_rank, y = Total.Budget, color=Continent)) + 
  geom_point(size=3, alpha=0.5, position="jitter")+ 
  coord_cartesian(ylim=c(0,3000000))

ggplot( data = fifa, aes(x = Project.Approval.Year, y = Total.Budget)) + geom_boxplot()+
  coord_cartesian(ylim=c(0,2000000))
#Распределение бюджеттов по годам
ggplot( data = fifa, aes(x = Project.Approval.Year, y = Total.Budget)) + 
  geom_boxplot()+
  coord_cartesian(ylim=c(0,2000000))

ggplot( data = fifa, aes(x = Total.Budget, color=Project.Approval.Year ))+
  geom_density(size = 1)+
  coord_cartesian(xlim=c(0,1500000))

```


#Финальные графики
```{r}
#Группировка по странам
fifa.fifa_by_country <- fifa %>%
    group_by(Country, id) %>%
    summarise(
          TotalBudget = sum(as.numeric(Total.Budget)),
          n=n()) 

#Группировка по странам и годам. Создание Широкой таблицы, каждый год - столбец
#Project.Approval.Year
fifa.fifa_by_country_year <- fifa %>%
    group_by(Country, id, Project.Approval.Year) %>%
    summarise(
          TotalBudget = sum(as.numeric(Total.Budget)),
          n=n()) 

fifa.fifa_by_country_year <- dcast(fifa.fifa_by_country_year, Country + id ~ Project.Approval.Year, value.var = "TotalBudget")

#Группировка по классам проектов
fifa.fifa_by_class <- fifa %>%
    group_by(Class) %>%
    summarise(
          TotalBudget = sum(as.numeric(Total.Budget)),
          n=n())

#Группировка по регионам
fifa.fifa_by_region <- fifa %>%
    group_by(Region) %>%
    summarise(
          TotalBudget = sum(as.numeric(Total.Budget)),
          n=n())

#Группировка по регионам и классам 
fifa.fifa_by_region_class <- fifa %>%
    group_by(Region, Class) %>%
    summarise(
          TotalBudget = sum(as.numeric(Total.Budget)),
          n=n())

fifa.fifa_by_region_class <- dcast(fifa.fifa_by_region_class, Region ~ Class, value.var = "TotalBudget")



###############################################################################
#Группировка по годам проектов
fifa.fifa_by_year <- fifa %>%
    group_by(Project.Approval.Year) %>%
    summarise(
          budget_median = median(as.numeric(Total.Budget)),
          budget_sum = sum(as.numeric(Total.Budget)),
          n=n())

head(fifa.fifa_by_year,20)


#Группировка по годам и классам проектов
fifa.fifa_by_year_class <- fifa %>%
    group_by(Project.Approval.Year, Class) %>%
    summarise(
          budget_median = median(as.numeric(Total.Budget)),
          budget_sum = sum(as.numeric(Total.Budget)),
          n=n())

fifa.fifa_by_year_region <- fifa %>%
    group_by(Project.Approval.Year, Region) %>%
    summarise(
          budget_median = median(as.numeric(Total.Budget)),
          budget_sum = sum(as.numeric(Total.Budget)),
          n=n())


##################################
fifa.fifa_by_country <- fifa.fifa_by_country[order(fifa.fifa_by_country$budget_sum, decreasing=T), ]
fifa.fifa_by_country <- transform(fifa.fifa_by_country, 
                          Country = reorder(Country, budget_sum))

                    
ggplot( data = head(fifa.fifa_by_country,40), aes(x = Country, y= budget_sum)) + 
  geom_bar(stat='identity', fill="steelblue", color="white")+ 
  coord_flip()+
  ggtitle('Суммы бюджетов по странам')

##################################
#По классу проектов
fifa.fifa_by_class <- fifa.fifa_by_class[order(fifa.fifa_by_class$budget_sum, decreasing=T), ]
fifa.fifa_by_class <- transform(fifa.fifa_by_class, 
                          Class = reorder(Class, budget_sum))

                    
ggplot( data = fifa.fifa_by_class, aes(x = Class, y= budget_sum)) + 
  geom_bar(stat='identity', fill="steelblue", color="white")+ 
  coord_flip()+
  ggtitle('Классы проектов по сумме бюджетов')

fifa.fifa_by_class <- transform(fifa.fifa_by_class, 
                          Class = reorder(Class, budget_median))

                    
ggplot( data = fifa.fifa_by_class, aes(x = Class, y= budget_median)) +
  geom_bar(stat='identity', fill="steelblue", color="white")+ 
  coord_flip()+
  ggtitle('Классы проектов по медиане бюджетов')
#################################
fifa.fifa_by_region <- transform(fifa.fifa_by_region, 
                          Region = reorder(Region, budget_median))

ggplot( data = fifa.fifa_by_region, aes(x = Region, y= budget_median)) + 
  geom_bar(stat='identity', fill="steelblue", color="white")+ 
  coord_flip() +
  ggtitle('Регионы проектов по медиане бюджетов')

fifa.fifa_by_region <- transform(fifa.fifa_by_region, 
                          Region = reorder(Region, budget_sum))

ggplot( data = fifa.fifa_by_region, aes(x = Region, y= budget_sum)) + 
  geom_bar(stat='identity', fill="steelblue", color="white")+ 
  coord_flip() +
  ggtitle('Регионы проектов по сумме бюджетов')

#################################
#Регионы бюджетов по классам
fifa.fifa_by_region_class <- transform(fifa.fifa_by_region_class, 
                          Region = reorder(Region, budget_sum))

ggplot( data = fifa.fifa_by_region_class, aes(x = Region,                                              y= budget_sum, fill = Class)) + 
  geom_bar(stat='identity')+ 
  coord_flip()

#################################
#годы бюджетов по классам
ggplot( data = fifa.fifa_by_year_class, aes(x = Project.Approval.Year,                                              y= budget_sum, fill = Class)) + 
  geom_bar(stat='identity')

#Количество бюджетов по годам и классам
ggplot( data = fifa.fifa_by_year_class, aes(x = Project.Approval.Year,                                              y= n, fill = Class)) + 
  geom_bar(stat='identity')


ggplot( data = fifa.fifa_by_year_region, aes(x = Project.Approval.Year,                                              y= budget_sum, fill = Region)) + 
  geom_bar(stat='identity')

ggplot( data = fifa.fifa_by_year_class, aes(x = Project.Approval.Year,                                              y= class, size = budget_sum)) + 
  geom_point()



#################################
#Распределение бюджеттов по годам
ggplot( data = fifa, aes(x = Project.Approval.Year, y = Total.Budget)) + 
  geom_boxplot()+
  coord_cartesian(ylim=c(0,2000000))+
  ggtitle('Распределение бюджеттов по годам')




###################################
#Budget Heat map by year
 ggplot(data = fifa.fifa_by_year_class, aes(x = Project.Approval.Year,y = Class)) + geom_tile(aes(fill = budget_sum),colour = "white") + 
  scale_fill_gradient(low = "white", high = "steelblue") + theme_bw()

 ggplot(data = fifa.fifa_by_year_class, aes(x = Project.Approval.Year,y = Class)) + geom_tile(aes(fill = n),colour = "white") + 
  scale_fill_gradient(low = "white", high = "steelblue") + theme_bw()

 ggplot(data = fifa.fifa_by_year_region, aes(x = Project.Approval.Year,y = Region)) + geom_tile(aes(fill = budget_sum),colour = "white") + 
  scale_fill_gradient(low = "white", high = "steelblue") + theme_bw()

 ggplot(data = fifa.fifa_by_year_region, aes(x = Project.Approval.Year,y = Region)) + geom_tile(aes(fill = n),colour = "white") + 
  scale_fill_gradient(low = "white", high = "steelblue") + theme_bw()

 ggplot(data = fifa.fifa_by_year_region, aes(x = Project.Approval.Year,y = Region, size = budget_sum))+
  geom_point()

ggplot( data = fifa.fifa_by_year, aes(x = Project.Approval.Year, y= budget_sum)) + 
  geom_bar(stat='identity', fill="steelblue", color="white")+ 
  ggtitle('Бюджеты по годам')

ggplot( data = fifa, aes(x = Project.Approval.Year)) + 
  geom_histogram(fill="steelblue", color="white")+ 
  ggtitle('Распределение Бюджеты по годам')  

###Как изменялся рейтинг стран в зависимости от финансирования

fifa.fifa_by_country <- transform(fifa.fifa_by_country, 
                          Country = reorder(Country, budget_sum))

ggplot(data = subset(fifa.fifa_by_country, diff_rank > 0), aes(y = diff_rank,x = budget_sum)) + geom_point()+
  coord_cartesian(xlim=c(0,7500000))+
  geom_smooth(method = "lm")

```